# Generated by Django 5.1.4 on 2026-05-02 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('WAITING_PARTS', 'Esperando repuestos'), ('DONE', 'Terminada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('service_date', models.DateField(verbose_name='Fecha de servicio')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje')),
                ('customer_complaint', models.TextField(verbose_name='Motivo reportado por cliente')),
                ('mechanic_observations', models.TextField(blank=True, verbose_name='Observaciones del mecánico')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('work_done', models.TextField(blank=True, verbose_name='Trabajo realizado')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('mechanic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_orders', to=settings.AUTH_USER_MODEL, verbose_name='Mecánico')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='vehicles.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Orden de servicio',
                'verbose_name_plural': 'Órdenes de servicio',
                'ordering': ['-service_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('hours', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Horas')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por hora')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo por hora')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labors', to='service_orders.serviceorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Mano de obra',
                'verbose_name_plural': 'Mano de obra',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('name', models.CharField(max_length=200, verbose_name='Repuesto')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo unitario')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='service_orders.serviceorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
            },
        ),
        migrations.CreateModel(
            name='ServiceOrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('image', models.ImageField(upload_to='service_orders/%Y/%m/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, verbose_name='Visible en vista pública')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service_orders.serviceorder', verbose_name='Orden')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subida por')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expira el')),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_token', to='service_orders.serviceorder', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Token compartido',
                'verbose_name_plural': 'Tokens compartidos',
            },
        ),
    ]
