# Generated by Django 5.1.4 on 2026-05-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosticRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('prompt', models.TextField(verbose_name='Consulta enviada')),
                ('response', models.TextField(blank=True, verbose_name='Respuesta de la IA')),
                ('model_used', models.CharField(default='gemini-1.5-flash', max_length=60, verbose_name='Modelo usado')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tokens utilizados')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_diagnostics', to='service_orders.serviceorder', verbose_name='Orden de servicio')),
            ],
            options={
                'verbose_name': 'Diagnóstico IA',
                'verbose_name_plural': 'Diagnósticos IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
