# Generated by Django 5.1.4 on 2026-05-02 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('brand', models.CharField(max_length=60, verbose_name='Marca')),
                ('model', models.CharField(max_length=60, verbose_name='Modelo')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Patente')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='Número de serie (VIN)')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='Color')),
                ('engine', models.CharField(blank=True, max_length=60, verbose_name='Motor')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['brand', 'model'],
            },
        ),
    ]
